# Generated by Django 5.0.4 on 2024-05-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='role',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
