# Generated by Django 5.0.4 on 2024-04-23 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='urlsy',
            field=models.CharField(blank=True, null=True),
        ),
    ]
