# Generated by Django 5.0.4 on 2024-05-04 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_authuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='company_name',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='date_modified',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='is_growing',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='price',
        ),
        migrations.AddField(
            model_name='stock',
            name='date_and_time',
            field=models.DateTimeField(null=True, verbose_name='Дата и время консультации'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stocks.authuser', verbose_name='Создатель заявки'),
        ),
    ]
