# Generated by Django 5.0.4 on 2024-04-23 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_teachers_urlsy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='urlsy',
        ),
    ]
