# Generated by Django 5.0.4 on 2024-05-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_remove_stock_company_name_remove_stock_date_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='teacher',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Преподаватель, которому назначена консультация'),
        ),
    ]
