# Generated by Django 5.0.4 on 2024-05-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_stock_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='teacher',
            field=models.CharField(blank=True, default='Преподаватель', max_length=255, verbose_name='Преподаватель, которому назначена консультация'),
        ),
    ]
