# Generated by Django 5.0.4 on 2024-04-23 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_teachers_urls4'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teachers',
            name='urls4',
        ),
    ]
