# Generated by Django 5.0.4 on 2024-05-29 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_alter_stock_status_alter_stock_teacher_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('teacher', 'Manager')], max_length=20),
        ),
    ]
