# Generated by Django 5.0.4 on 2024-05-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_alter_stock_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='teacher',
        ),
        migrations.AddField(
            model_name='stock',
            name='teacherid',
            field=models.IntegerField(null=True),
        ),
    ]
