# Generated by Django 5.0.4 on 2024-04-24 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0005_remove_teachers_urls4'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teachers',
            old_name='urls',
            new_name='url',
        ),
    ]
