# Generated by Django 5.0.4 on 2024-05-04 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0006_remove_stock_teacher_stock_teacherid'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='status',
            field=models.CharField(default='В работе', max_length=150),
        ),
    ]
