# Generated by Django 5.0.4 on 2024-05-06 18:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stocks.teacher', verbose_name='Преподаватель'),
        ),
    ]
