# Generated by Django 5.0.4 on 2024-05-30 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0008_stock_teacher_alter_stock_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='teacher',
        ),
    ]
