# Generated by Django 5.0.4 on 2024-05-07 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0009_stock_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authuser',
            name='role',
        ),
        migrations.RemoveField(
            model_name='authuser',
            name='username',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='username',
        ),
    ]
