# Generated by Django 5.0.4 on 2024-05-07 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0011_rename_teacher_stock_teacher_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='teacher_id',
            new_name='teacher',
        ),
        migrations.RenameField(
            model_name='stock',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddField(
            model_name='stock',
            name='teacherid',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='stock',
            name='userid',
            field=models.IntegerField(default=1),
        ),
    ]
