# Generated by Django 5.0.4 on 2024-05-08 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0013_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stocks.teacher', verbose_name='Преподаватель'),
        ),
        migrations.AddField(
            model_name='subject',
            name='teacherid',
            field=models.IntegerField(default=1),
        ),
    ]
