# Generated by Django 5.0.4 on 2024-05-30 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0013_stock_subject_alter_uslugi_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='subject',
        ),
    ]
