# Generated by Django 5.0.4 on 2024-05-31 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0014_remove_stock_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User'), ('teacher', 'Teacher')], max_length=20),
        ),
        migrations.AlterField(
            model_name='stock',
            name='status',
            field=models.CharField(choices=[('Черновик', 'Pending'), ('Завершена', 'Approved'), ('Отклонена', 'Rejected')], default='Черновик', max_length=10),
        ),
    ]
