# Generated by Django 5.0.4 on 2024-05-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0015_uslugi_alter_subject_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks_Uslugi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockid', models.IntegerField(default=1)),
                ('uslugaid', models.IntegerField(default=1)),
            ],
        ),
        migrations.AddField(
            model_name='stock',
            name='create_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='stock',
            name='end_date',
            field=models.DateTimeField(null=True),
        ),
    ]
