# Generated by Django 5.0.4 on 2024-05-14 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0016_stocks_uslugi_stock_create_date_stock_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='stocks_uslugi',
            name='stock',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stocks.stock', verbose_name='Заявка'),
        ),
        migrations.AddField(
            model_name='stocks_uslugi',
            name='usluga',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stocks.uslugi', verbose_name='Услуга'),
        ),
    ]
