# Generated by Django 5.0.4 on 2024-05-31 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0017_alter_appuser_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='username',
        ),
    ]
