# Generated by Django 5.0.4 on 2024-05-14 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0017_stock_is_active_stocks_uslugi_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='uslugi',
            field=models.ManyToManyField(to='stocks.uslugi'),
        ),
        migrations.DeleteModel(
            name='Stocks_Uslugi',
        ),
    ]
