# Generated by Django 5.0.4 on 2024-05-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0018_stock_uslugi_delete_stocks_uslugi'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='uslugiid',
            field=models.JSONField(default=list),
        ),
    ]
