# Generated by Django 5.0.4 on 2024-05-16 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0019_stock_uslugiid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='teacherid',
        ),
        migrations.AlterField(
            model_name='stock',
            name='status',
            field=models.CharField(default='Черновик', max_length=150),
        ),
    ]
