# Generated by Django 5.0.4 on 2024-05-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0020_remove_subject_teacherid_alter_stock_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='uslugi',
            field=models.ManyToManyField(to='stocks.uslugi', verbose_name='Услуги'),
        ),
    ]
