# Generated by Django 5.0.4 on 2024-05-16 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0021_alter_stock_uslugi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='teacherid',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='userid',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='uslugiid',
        ),
    ]
