# Generated by Django 5.0.4 on 2024-05-17 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0022_remove_stock_teacherid_remove_stock_userid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='uslugi',
        ),
        migrations.AddField(
            model_name='uslugi',
            name='stocks',
            field=models.ManyToManyField(to='stocks.stock', verbose_name='Заявки'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='user',
            field=models.ForeignKey(default=16, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stocks.authuser', verbose_name='Создатель заявки'),
        ),
    ]
