# Generated by Django 5.0.4 on 2024-05-17 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0023_remove_stock_uslugi_uslugi_stocks_alter_stock_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uslugi',
            name='stocks',
        ),
        migrations.AddField(
            model_name='stock',
            name='uslugi',
            field=models.ManyToManyField(to='stocks.uslugi', verbose_name='Услуги'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='stocks.authuser', verbose_name='Создатель заявки'),
        ),
    ]
